name: Check diff of HTML files

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every hour on the hour
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  backup:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests git-python beautifulsoup4


      - name: Configure Git user identity
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
      - name: Run backup script
        run: |
          python backup_script.py

      - name: Commit changes
        run: |
          git diff --quiet
          if [ $? -ne 0 ]; then
            git add .
            git commit -m "Backup update for $(date +%Y-%m-%d)"
            git push origin main
            echo "backup_updated=true" >> $GITHUB_OUTPUT
          else
            echo "backup_updated=false" >> $GITHUB_OUTPUT
          fi
          
  check-diff:
    runs-on: ubuntu-latest
    needs: backup
    steps:
      - uses: actions/checkout@v2

      - name: Check diff
        env:
          TZ: Asia/Ho_Chi_Minh
        run: |
          # Get the hash of the previous commit
          previous_commit=$(git rev-parse HEAD^)
          
          for filename in $(find . -name '*.html'); do
            # Check for deleted files
            if [ ! -f "$filename" ]; then
              echo "$filename was deleted!"
              curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
                -d "{ \"body\": \"[HTML Diff Check] The support article file \`$filename\` has been deleted in this commit.\" }"
            fi
            
            # Check for renamed files
            new_filename=$(git diff --no-index --name-only "$filename" "$previous_commit:$filename")
            if [ -n "$new_filename" ] && [ "$filename" != "$new_filename" ]; then
              echo "$filename was renamed to $new_filename!"
              curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
                -d "{ \"body\": \"[HTML Diff Check] The support article file \`$filename\` has been renamed to \`$new_filename\` in this commit.\" }"
            fi

            # Check for modified files
            result=$(git diff --no-index --word-diff=porcelain "$filename" "$previous_commit:$filename" | grep -E '^\+[^\+]|^\-[^\-]')
            if [ "$result" != "" ]; then
              echo "$result"
              curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
                -d "{ \"body\": \"[HTML Diff Check] HTML diff detected in \`$filename\`.\\\n\\\n\`\`\`$result\`\`\`\" }"
            fi
          done
