name: Check diff of HTML files
on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write

jobs:
  backup:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests git-python beautifulsoup4
      - name: Configure Git user identity
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
      - name: Run backup script
        run: |
          python backup_script.py
      - name: Commit changes
        run: |
          now=$(date +"%d-%m-%Y %H-%M")
          git diff --quiet
          if [ $? -ne 0 ]; then
            git add .
            git commit -m "Article Datamining - $now"
            git push origin main
            echo "backup_updated=true" >> $GITHUB_OUTPUT
          else
            echo "backup_updated=false" >> $GITHUB_OUTPUT
          fi
  check-diff:
    runs-on: ubuntu-latest
    needs: backup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Check diff and post comments
        run: |
          # Get the hash of the previous commit
          previous_commit=$(git rev-parse HEAD^)
          
          # Check for deleted files
          for filename in $(git diff --name-only "$previous_commit" | grep -E '^en-us/.*\.html$' | xargs -I'{}' sh -c 'git cat-file -e "$1":{} > /dev/null 2>&1 && echo "{}"' -- {}); do
            if [ ! -f "$filename" ]; then
              echo "Deleted Article: \`$filename\`"
              python -c "import requests;requests.post(f'https://api.github.com/repos/{os.environ['GITHUB_REPOSITORY']}/commits/{os.environ['GITHUB_SHA']}/comments', headers={'Authorization': f'Bearer {os.environ['GITHUB_TOKEN']}','Accept':'application/vnd.github.v3+json'}, json={'body': '[HTML Diff Check] The support article file `$filename` has been deleted in this commit.'})"
            fi
          done
          # Check for modified files
          for filename in $(git diff --name-only "$previous_commit" | grep -E '^en-us/.*\.html$' | xargs -I'{}' sh -c 'git cat-file -e "$1":{} > /dev/null 2>&1 && echo "{}"' -- {}); do
            result=$(git diff --no-index --word-diff=porcelain "$filename" "$previous_commit:$filename" | grep -E '^\+[^\+]|^\-[^\-]')
            if [ "$result" != "" ]; then
              echo "Modified Article: \`$filename\`"
              echo "~~~" && echo "$result" && echo "~~~"
              python -c "import requests;requests.post(f'https://api.github.com/repos/{os.environ['GITHUB_REPOSITORY']}/commits/{os.environ['GITHUB_SHA']}/comments', headers={'Authorization': f'Bearer {os.environ['GITHUB_TOKEN']}','Accept':'application/vnd.github.v3+json'}, json={'body': '[HTML Diff Check] HTML diff detected in `$filename`.\n\n```\n$result\n```'})"
            fi
          done
          # Check for added files
          for filename in $(git diff --name-only "$previous_commit" | grep -E '^en-us/.*\.html$' | xargs -I'{}' sh -c 'git cat-file -e "$1":{} > /dev/null 2>&1 && echo "{}"' -- {}); do
            if [ ! -f "$filename" ]; then
              echo "Added Article: \`$filename\`"
              python -c "import requests;requests.post(f'https://api.github.com/repos/{os.environ['GITHUB_REPOSITORY']}/commits/{os.environ['GITHUB_SHA']}/comments', headers={'Authorization': f'Bearer {os.environ['GITHUB_TOKEN']}','Accept':'application/vnd.github.v3+json'}, json={'body': '[HTML Diff Check] The support article file `$filename` has been added in this commit.'})" 
            fi
          done
