name: Check diff of HTML files

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests git-python

      - name: Run backup script
        run: |
          python backup_script.py

      - name: Configure Git user identity
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Commit changes
        run: |
          git diff --quiet
          if [ $? -ne 0 ]; then
            git add .
            git commit -m "Backup update for $(date +%Y-%m-%d)"
            git push origin main
            echo "::set-output name=backup_updated::true"
          else
            echo "::set-output name=backup_updated::false"
          fi

  check-diff:
    runs-on: ubuntu-latest
    needs: backup
    if: ${{ needs.backup.outputs.backup_updated == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Check diff
        env:
          TZ: Asia/Ho_Chi_Minh
        run: |
          before_dir="backup/$(date --date=yesterday +%Y-%m-%d)"
          after_dir="backup/$(date +%Y-%m-%d)"

          # Check diff and post comment
          if [ -d "$before_dir" ]; then
            echo "Checking diff for files in $before_dir"
            for filename in $(find "$before_dir" -name '*.html'); do
              echo "Checking diff for $filename"
              result=$(git diff "$before_dir" "$after_dir" --word-diff=porcelain -- "$filename" | grep -E '^\+[^\+]|^\-[^\-]')
              if [ "$result" != "" ]; then
                echo "$result"
                curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                  -H "Accept: application/vnd.github.v3+json" \
                  https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments \
                  -d "{ \"body\": \"[HTML Diff Check] HTML diff detected in $filename.\\\n\\\n\`\`\`$result\`\`\`\" }"
              fi
            done
          fi
